---
id: Secret
name: Secret
full: Secret key encryption library
description: >-
  A library for encrypting and decrypting small pieces of data with the use of a
  shared key.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Secret
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/crypt_blowfish: ^2
      horde/exception: ^3
      horde/support: ^3
    ext:
      hash: '*'
  optional:
    composer:
      horde/test: ^3
